// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demopojo.proto

package yuanjun.chen.serialize.protobuf.dto;

public final class DemoDtoModule {
  private DemoDtoModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DemoDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DemoDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 自增主键
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     * 交货期
     * </pre>
     *
     * <code>optional int64 deliveryDateRaw = 2;</code>
     */
    long getDeliveryDateRaw();

    /**
     * <pre>
     * 紧急程度
     * </pre>
     *
     * <code>optional int32 urgentDegree = 3;</code>
     */
    int getUrgentDegree();

    /**
     * <pre>
     * 转义为double
     * </pre>
     *
     * <code>optional double materialCost = 4;</code>
     */
    double getMaterialCost();

    /**
     * <pre>
     * 转义为double
     * </pre>
     *
     * <code>optional double remunerateCost = 5;</code>
     */
    double getRemunerateCost();

    /**
     * <pre>
     * 运输优先级
     * </pre>
     *
     * <code>optional int32 transportPriority = 6;</code>
     */
    int getTransportPriority();

    /**
     * <pre>
     * 预留优先级A
     * </pre>
     *
     * <code>optional int32 reservedPriorityA = 7;</code>
     */
    int getReservedPriorityA();

    /**
     * <pre>
     * 预留优先级B
     * </pre>
     *
     * <code>optional int32 reservedPriorityB = 8;</code>
     */
    int getReservedPriorityB();

    /**
     * <pre>
     * 预留优先级C	
     * </pre>
     *
     * <code>optional int32 reservedPriorityC = 9;</code>
     */
    int getReservedPriorityC();
  }
  /**
   * Protobuf type {@code DemoDto}
   */
  public  static final class DemoDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DemoDto)
      DemoDtoOrBuilder {
    // Use DemoDto.newBuilder() to construct.
    private DemoDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemoDto() {
      id_ = 0L;
      deliveryDateRaw_ = 0L;
      urgentDegree_ = 0;
      materialCost_ = 0D;
      remunerateCost_ = 0D;
      transportPriority_ = 0;
      reservedPriorityA_ = 0;
      reservedPriorityB_ = 0;
      reservedPriorityC_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DemoDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              deliveryDateRaw_ = input.readInt64();
              break;
            }
            case 24: {

              urgentDegree_ = input.readInt32();
              break;
            }
            case 33: {

              materialCost_ = input.readDouble();
              break;
            }
            case 41: {

              remunerateCost_ = input.readDouble();
              break;
            }
            case 48: {

              transportPriority_ = input.readInt32();
              break;
            }
            case 56: {

              reservedPriorityA_ = input.readInt32();
              break;
            }
            case 64: {

              reservedPriorityB_ = input.readInt32();
              break;
            }
            case 72: {

              reservedPriorityC_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.internal_static_DemoDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.internal_static_DemoDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto.class, yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * 自增主键
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int DELIVERYDATERAW_FIELD_NUMBER = 2;
    private long deliveryDateRaw_;
    /**
     * <pre>
     * 交货期
     * </pre>
     *
     * <code>optional int64 deliveryDateRaw = 2;</code>
     */
    public long getDeliveryDateRaw() {
      return deliveryDateRaw_;
    }

    public static final int URGENTDEGREE_FIELD_NUMBER = 3;
    private int urgentDegree_;
    /**
     * <pre>
     * 紧急程度
     * </pre>
     *
     * <code>optional int32 urgentDegree = 3;</code>
     */
    public int getUrgentDegree() {
      return urgentDegree_;
    }

    public static final int MATERIALCOST_FIELD_NUMBER = 4;
    private double materialCost_;
    /**
     * <pre>
     * 转义为double
     * </pre>
     *
     * <code>optional double materialCost = 4;</code>
     */
    public double getMaterialCost() {
      return materialCost_;
    }

    public static final int REMUNERATECOST_FIELD_NUMBER = 5;
    private double remunerateCost_;
    /**
     * <pre>
     * 转义为double
     * </pre>
     *
     * <code>optional double remunerateCost = 5;</code>
     */
    public double getRemunerateCost() {
      return remunerateCost_;
    }

    public static final int TRANSPORTPRIORITY_FIELD_NUMBER = 6;
    private int transportPriority_;
    /**
     * <pre>
     * 运输优先级
     * </pre>
     *
     * <code>optional int32 transportPriority = 6;</code>
     */
    public int getTransportPriority() {
      return transportPriority_;
    }

    public static final int RESERVEDPRIORITYA_FIELD_NUMBER = 7;
    private int reservedPriorityA_;
    /**
     * <pre>
     * 预留优先级A
     * </pre>
     *
     * <code>optional int32 reservedPriorityA = 7;</code>
     */
    public int getReservedPriorityA() {
      return reservedPriorityA_;
    }

    public static final int RESERVEDPRIORITYB_FIELD_NUMBER = 8;
    private int reservedPriorityB_;
    /**
     * <pre>
     * 预留优先级B
     * </pre>
     *
     * <code>optional int32 reservedPriorityB = 8;</code>
     */
    public int getReservedPriorityB() {
      return reservedPriorityB_;
    }

    public static final int RESERVEDPRIORITYC_FIELD_NUMBER = 9;
    private int reservedPriorityC_;
    /**
     * <pre>
     * 预留优先级C	
     * </pre>
     *
     * <code>optional int32 reservedPriorityC = 9;</code>
     */
    public int getReservedPriorityC() {
      return reservedPriorityC_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (deliveryDateRaw_ != 0L) {
        output.writeInt64(2, deliveryDateRaw_);
      }
      if (urgentDegree_ != 0) {
        output.writeInt32(3, urgentDegree_);
      }
      if (materialCost_ != 0D) {
        output.writeDouble(4, materialCost_);
      }
      if (remunerateCost_ != 0D) {
        output.writeDouble(5, remunerateCost_);
      }
      if (transportPriority_ != 0) {
        output.writeInt32(6, transportPriority_);
      }
      if (reservedPriorityA_ != 0) {
        output.writeInt32(7, reservedPriorityA_);
      }
      if (reservedPriorityB_ != 0) {
        output.writeInt32(8, reservedPriorityB_);
      }
      if (reservedPriorityC_ != 0) {
        output.writeInt32(9, reservedPriorityC_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (deliveryDateRaw_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, deliveryDateRaw_);
      }
      if (urgentDegree_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, urgentDegree_);
      }
      if (materialCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, materialCost_);
      }
      if (remunerateCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, remunerateCost_);
      }
      if (transportPriority_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, transportPriority_);
      }
      if (reservedPriorityA_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, reservedPriorityA_);
      }
      if (reservedPriorityB_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, reservedPriorityB_);
      }
      if (reservedPriorityC_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, reservedPriorityC_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto)) {
        return super.equals(obj);
      }
      yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto other = (yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getDeliveryDateRaw()
          == other.getDeliveryDateRaw());
      result = result && (getUrgentDegree()
          == other.getUrgentDegree());
      result = result && (
          java.lang.Double.doubleToLongBits(getMaterialCost())
          == java.lang.Double.doubleToLongBits(
              other.getMaterialCost()));
      result = result && (
          java.lang.Double.doubleToLongBits(getRemunerateCost())
          == java.lang.Double.doubleToLongBits(
              other.getRemunerateCost()));
      result = result && (getTransportPriority()
          == other.getTransportPriority());
      result = result && (getReservedPriorityA()
          == other.getReservedPriorityA());
      result = result && (getReservedPriorityB()
          == other.getReservedPriorityB());
      result = result && (getReservedPriorityC()
          == other.getReservedPriorityC());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + DELIVERYDATERAW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeliveryDateRaw());
      hash = (37 * hash) + URGENTDEGREE_FIELD_NUMBER;
      hash = (53 * hash) + getUrgentDegree();
      hash = (37 * hash) + MATERIALCOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaterialCost()));
      hash = (37 * hash) + REMUNERATECOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRemunerateCost()));
      hash = (37 * hash) + TRANSPORTPRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getTransportPriority();
      hash = (37 * hash) + RESERVEDPRIORITYA_FIELD_NUMBER;
      hash = (53 * hash) + getReservedPriorityA();
      hash = (37 * hash) + RESERVEDPRIORITYB_FIELD_NUMBER;
      hash = (53 * hash) + getReservedPriorityB();
      hash = (37 * hash) + RESERVEDPRIORITYC_FIELD_NUMBER;
      hash = (53 * hash) + getReservedPriorityC();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DemoDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DemoDto)
        yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.internal_static_DemoDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.internal_static_DemoDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto.class, yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto.Builder.class);
      }

      // Construct using yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        deliveryDateRaw_ = 0L;

        urgentDegree_ = 0;

        materialCost_ = 0D;

        remunerateCost_ = 0D;

        transportPriority_ = 0;

        reservedPriorityA_ = 0;

        reservedPriorityB_ = 0;

        reservedPriorityC_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.internal_static_DemoDto_descriptor;
      }

      public yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto getDefaultInstanceForType() {
        return yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto.getDefaultInstance();
      }

      public yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto build() {
        yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto buildPartial() {
        yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto result = new yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto(this);
        result.id_ = id_;
        result.deliveryDateRaw_ = deliveryDateRaw_;
        result.urgentDegree_ = urgentDegree_;
        result.materialCost_ = materialCost_;
        result.remunerateCost_ = remunerateCost_;
        result.transportPriority_ = transportPriority_;
        result.reservedPriorityA_ = reservedPriorityA_;
        result.reservedPriorityB_ = reservedPriorityB_;
        result.reservedPriorityC_ = reservedPriorityC_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto) {
          return mergeFrom((yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto other) {
        if (other == yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getDeliveryDateRaw() != 0L) {
          setDeliveryDateRaw(other.getDeliveryDateRaw());
        }
        if (other.getUrgentDegree() != 0) {
          setUrgentDegree(other.getUrgentDegree());
        }
        if (other.getMaterialCost() != 0D) {
          setMaterialCost(other.getMaterialCost());
        }
        if (other.getRemunerateCost() != 0D) {
          setRemunerateCost(other.getRemunerateCost());
        }
        if (other.getTransportPriority() != 0) {
          setTransportPriority(other.getTransportPriority());
        }
        if (other.getReservedPriorityA() != 0) {
          setReservedPriorityA(other.getReservedPriorityA());
        }
        if (other.getReservedPriorityB() != 0) {
          setReservedPriorityB(other.getReservedPriorityB());
        }
        if (other.getReservedPriorityC() != 0) {
          setReservedPriorityC(other.getReservedPriorityC());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * 自增主键
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 自增主键
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 自增主键
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long deliveryDateRaw_ ;
      /**
       * <pre>
       * 交货期
       * </pre>
       *
       * <code>optional int64 deliveryDateRaw = 2;</code>
       */
      public long getDeliveryDateRaw() {
        return deliveryDateRaw_;
      }
      /**
       * <pre>
       * 交货期
       * </pre>
       *
       * <code>optional int64 deliveryDateRaw = 2;</code>
       */
      public Builder setDeliveryDateRaw(long value) {
        
        deliveryDateRaw_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交货期
       * </pre>
       *
       * <code>optional int64 deliveryDateRaw = 2;</code>
       */
      public Builder clearDeliveryDateRaw() {
        
        deliveryDateRaw_ = 0L;
        onChanged();
        return this;
      }

      private int urgentDegree_ ;
      /**
       * <pre>
       * 紧急程度
       * </pre>
       *
       * <code>optional int32 urgentDegree = 3;</code>
       */
      public int getUrgentDegree() {
        return urgentDegree_;
      }
      /**
       * <pre>
       * 紧急程度
       * </pre>
       *
       * <code>optional int32 urgentDegree = 3;</code>
       */
      public Builder setUrgentDegree(int value) {
        
        urgentDegree_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 紧急程度
       * </pre>
       *
       * <code>optional int32 urgentDegree = 3;</code>
       */
      public Builder clearUrgentDegree() {
        
        urgentDegree_ = 0;
        onChanged();
        return this;
      }

      private double materialCost_ ;
      /**
       * <pre>
       * 转义为double
       * </pre>
       *
       * <code>optional double materialCost = 4;</code>
       */
      public double getMaterialCost() {
        return materialCost_;
      }
      /**
       * <pre>
       * 转义为double
       * </pre>
       *
       * <code>optional double materialCost = 4;</code>
       */
      public Builder setMaterialCost(double value) {
        
        materialCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 转义为double
       * </pre>
       *
       * <code>optional double materialCost = 4;</code>
       */
      public Builder clearMaterialCost() {
        
        materialCost_ = 0D;
        onChanged();
        return this;
      }

      private double remunerateCost_ ;
      /**
       * <pre>
       * 转义为double
       * </pre>
       *
       * <code>optional double remunerateCost = 5;</code>
       */
      public double getRemunerateCost() {
        return remunerateCost_;
      }
      /**
       * <pre>
       * 转义为double
       * </pre>
       *
       * <code>optional double remunerateCost = 5;</code>
       */
      public Builder setRemunerateCost(double value) {
        
        remunerateCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 转义为double
       * </pre>
       *
       * <code>optional double remunerateCost = 5;</code>
       */
      public Builder clearRemunerateCost() {
        
        remunerateCost_ = 0D;
        onChanged();
        return this;
      }

      private int transportPriority_ ;
      /**
       * <pre>
       * 运输优先级
       * </pre>
       *
       * <code>optional int32 transportPriority = 6;</code>
       */
      public int getTransportPriority() {
        return transportPriority_;
      }
      /**
       * <pre>
       * 运输优先级
       * </pre>
       *
       * <code>optional int32 transportPriority = 6;</code>
       */
      public Builder setTransportPriority(int value) {
        
        transportPriority_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 运输优先级
       * </pre>
       *
       * <code>optional int32 transportPriority = 6;</code>
       */
      public Builder clearTransportPriority() {
        
        transportPriority_ = 0;
        onChanged();
        return this;
      }

      private int reservedPriorityA_ ;
      /**
       * <pre>
       * 预留优先级A
       * </pre>
       *
       * <code>optional int32 reservedPriorityA = 7;</code>
       */
      public int getReservedPriorityA() {
        return reservedPriorityA_;
      }
      /**
       * <pre>
       * 预留优先级A
       * </pre>
       *
       * <code>optional int32 reservedPriorityA = 7;</code>
       */
      public Builder setReservedPriorityA(int value) {
        
        reservedPriorityA_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 预留优先级A
       * </pre>
       *
       * <code>optional int32 reservedPriorityA = 7;</code>
       */
      public Builder clearReservedPriorityA() {
        
        reservedPriorityA_ = 0;
        onChanged();
        return this;
      }

      private int reservedPriorityB_ ;
      /**
       * <pre>
       * 预留优先级B
       * </pre>
       *
       * <code>optional int32 reservedPriorityB = 8;</code>
       */
      public int getReservedPriorityB() {
        return reservedPriorityB_;
      }
      /**
       * <pre>
       * 预留优先级B
       * </pre>
       *
       * <code>optional int32 reservedPriorityB = 8;</code>
       */
      public Builder setReservedPriorityB(int value) {
        
        reservedPriorityB_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 预留优先级B
       * </pre>
       *
       * <code>optional int32 reservedPriorityB = 8;</code>
       */
      public Builder clearReservedPriorityB() {
        
        reservedPriorityB_ = 0;
        onChanged();
        return this;
      }

      private int reservedPriorityC_ ;
      /**
       * <pre>
       * 预留优先级C	
       * </pre>
       *
       * <code>optional int32 reservedPriorityC = 9;</code>
       */
      public int getReservedPriorityC() {
        return reservedPriorityC_;
      }
      /**
       * <pre>
       * 预留优先级C	
       * </pre>
       *
       * <code>optional int32 reservedPriorityC = 9;</code>
       */
      public Builder setReservedPriorityC(int value) {
        
        reservedPriorityC_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 预留优先级C	
       * </pre>
       *
       * <code>optional int32 reservedPriorityC = 9;</code>
       */
      public Builder clearReservedPriorityC() {
        
        reservedPriorityC_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:DemoDto)
    }

    // @@protoc_insertion_point(class_scope:DemoDto)
    private static final yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto();
    }

    public static yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DemoDto>
        PARSER = new com.google.protobuf.AbstractParser<DemoDto>() {
      public DemoDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DemoDto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoDto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemoDto> getParserForType() {
      return PARSER;
    }

    public yuanjun.chen.serialize.protobuf.dto.DemoDtoModule.DemoDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DemoDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DemoDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016demopojo.proto\"\336\001\n\007DemoDto\022\n\n\002id\030\001 \001(\003" +
      "\022\027\n\017deliveryDateRaw\030\002 \001(\003\022\024\n\014urgentDegre" +
      "e\030\003 \001(\005\022\024\n\014materialCost\030\004 \001(\001\022\026\n\016remuner" +
      "ateCost\030\005 \001(\001\022\031\n\021transportPriority\030\006 \001(\005" +
      "\022\031\n\021reservedPriorityA\030\007 \001(\005\022\031\n\021reservedP" +
      "riorityB\030\010 \001(\005\022\031\n\021reservedPriorityC\030\t \001(" +
      "\005B4\n#yuanjun.chen.serialize.protobuf.dto" +
      "B\rDemoDtoModuleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DemoDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DemoDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DemoDto_descriptor,
        new java.lang.String[] { "Id", "DeliveryDateRaw", "UrgentDegree", "MaterialCost", "RemunerateCost", "TransportPriority", "ReservedPriorityA", "ReservedPriorityB", "ReservedPriorityC", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
